mybatis:
  type-aliases-package: com.tcp.iamlazy
  config-location: classpath:mybatis/mapper/mybatis-config.xml

spring:
  profiles:
    include:
      - private
  http:
    log-request-details: true
  jpa:
    show-sql: true

logging:
  level:
    web: TRACE
    org:
      springframework:
        web: TRACE

server:
  port: 8092